databaseChangeLog:
  - changeSet:
      id: 6
      author: you
      changes:
        - dropTable:
            tableName: slot_product
        - dropTable:
            tableName: product

        - createTable:
            tableName: product
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: price
                  type: DECIMAL(10,2)
                  constraints:
                    nullable: false

        - createTable:
            tableName: slot_product
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: slot_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: product_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: quantity
                  type: INT
                  constraints:
                    nullable: false
        - addForeignKeyConstraint:
            baseTableName: slot_product
            baseColumnNames: slot_id
            referencedTableName: slot
            referencedColumnNames: id
            constraintName: fk_slot_product_slot
        - addForeignKeyConstraint:
            baseTableName: slot_product
            baseColumnNames: product_id
            referencedTableName: product
            referencedColumnNames: id
            constraintName: fk_slot_product_product